#!groovy
nice     = "nice -n 4"

SYSDEP   = "ykworkstation-intel"
BRANCH   = "develop"
MODEL    = "FElib"
TESTCASE = "test"
TESTNAME = ""
TESTTYPE = ""
VERSION  = "XXXXXXX"
STAMP    = "000000000000"

node("master") {
  timestamps {
    def workspace = pwd()
    sh "mkdir -p jenkins-scripts"

    dir("jenkins-scripts") {
        stage ("checkout jenkins-scripts from github") {
            checkout scm: [$class: "GitSCM", branches: [[name: "master"]],
                userRemoteConfigs: [[ credentialsId: "GitHub", url: "git@github.com:ywkawai/FE-Project_jenkins.git" ]]
            ]
        }
    }

    load "${workspace}/jenkins-scripts/common.groovy"

    dir("FE-Project/${MODEL}/src") {
        sh "which mpiifort && mpiifort -v"
        sh "which mpirun && mpirun -V"

        stage ("cleanup") {
            sh "make allclean"
        }

        stage ("build normal") {
            sh "make -j4"
        }
    }
    
    dir("FE-Project/${MODEL}/test/") {
        sh "which mpiifort && mpiifort -v"
        sh "which mpirun && mpirun -V"

      stage("common/linkedlist"){
        def TEST_RESULT0001=sh(script: """
          cd common/linkedlist/
          make clean          
          make && make run
        """) 
      }
      stage("common/linalgebra"){
        def TEST_RESULT0002=sh(script: """
          cd common/linalgebra/
          make clean          
          make && make run
        """) 
      }
      stage("common/time_manager"){
        def TEST_RESULT0003=sh(script: """
          cd common/time_manager/
          make clean          
          make && make run
        """) 
      }
      stage("common/sparsemat"){
        def TEST_RESULT0004=sh(script: """
          cd common/sparsemat
          make clean          
          make && make run
        """) 
      }
      stage("common/timeint_rk"){
        def TEST_RESULT0005=sh(script: """
          cd common/timeint_rk
          make clean          
          make && make run
        """) 
      }      
      stage("FE/polynominal"){
        def TEST_RESULT0101=sh(script: """
          cd FE/polynominal/
          make clean          
          make && make run
        """) 
      }    
      stage("FE/mesh_linedom1d"){
        def TEST_RESULT0102=sh(script: """
          cd FE/mesh_linedom1d/
          make clean          
          make && make run
        """) 
      }
      stage("FE/mesh_rectdom2d_quadrilateral"){
        def TEST_RESULT0103=sh(script: """
          cd FE/mesh_rectdom2d_quadrilateral/
          make clean          
          make && make run
        """) 
      }
      stage("FE/mesh_cubedsphere2d"){
        def TEST_RESULT0104=sh(script: """
          cd FE/mesh_cubedsphere2d/
          make clean          
          make && make run
        """) 
      }      
      stage("FE/mesh_cubedom3d_hexahedral"){
        def TEST_RESULT0105=sh(script: """
          cd FE/mesh_cubedom3d_hexahedral/
          make clean          
          make && make run
        """) 
      }
      stage("FE/mesh_cubedsphere3d"){
        def TEST_RESULT0106=sh(script: """
          cd FE/mesh_cubedsphere3d/
          make clean          
          make && make run
        """) 
      }       
      stage("FE/field_linedom1d"){
        def TEST_RESULT0107=sh(script: """
          cd FE/field_linedom1d/
          make clean          
          make && make run
        """) 
      }
      stage("FE/field_rectdom2d_quadrilateral"){
        def TEST_RESULT0108=sh(script: """
          cd FE/field_rectdom2d_quadrilateral/
          make clean          
          make && make run
        """) 
      }
      stage("FE/field_cubedspheredom2d"){
        def TEST_RESULT0109=sh(script: """
          cd FE/field_cubedspheredom2d/
          make clean          
          make && make run
        """) 
      }      
      stage("FE/field_cubedom3d_hexahedral"){
        def TEST_RESULT0110=sh(script: """
          cd FE/field_cubedom3d_hexahedral/
          make clean          
          make && make run
        """) 
      }
      stage("FE/field_cubedspheredom3d"){
        def TEST_RESULT0111=sh(script: """
          cd FE/field_cubedspheredom3d/
          make clean          
          make && make run
        """) 
      }          
      stage("framework/model_framework"){
        def TEST_RESULT0201=sh(script: """
          cd framework/model_framework/
          make clean          
          make && make run
        """) 
      }           
    }
  }
}
