#!groovy
nice     = "nice -n 4"

SYSDEP   = "FUGAKU-tcsds"
BRANCH   = "develop"
MODEL    = "FElib"
TESTCASE = "test"
TESTNAME = ""
TESTTYPE = ""
VERSION  = "XXXXXXX"
STAMP    = "000000000000"

node("FUGAKU") {
  timestamps {
    def workspace = pwd()
    sh "mkdir -p jenkins-scripts"

    dir("jenkins-scripts") {
        stage ("checkout jenkins-scripts from github") {
            checkout scm: [$class: "GitSCM", branches: [[name: "master"]],
                userRemoteConfigs: [[ credentialsId: "GitHub", url: "git@github.com:ywkawai/FE-Project_jenkins.git" ]]
            ]
        }
    }

    load "${workspace}/jenkins-scripts/common.groovy"

    dir("FE-Project/FElib/src") {
        sh "which mpifrtpx"

        stage ("cleanup") {
            sh "make allclean"
        }

        stage ("build normal") {
            sh "make -j4"
        }
    }

    dir("FE-Project/sample") {
      sh "which mpifrtpx"


      def sample_dir_path = pwd()
      def com_post = load "${workspace}/jenkins-scripts/common_post.groovy"

      stage("sample/advect1d"){
        // def TEST_RESULT1=sh(script: """
        //     cd ./advect1d
        //     make clean
        //     make
        //     make run
        //     export PATH=${env.PATH_ANALYSIS}; export LD_LIBRARY_PATH=${env.LD_LIBRARY_PATH_ANALYSIS}
        //     make vis
        // """)
        com_post.extract_run_LOG_info_remote( node_label: "FUGAKU", target_sample_dir: sample_dir_path, sample_name: "advect1d", log_fname: "LOG.pe000000")
        com_post.rsync_sample_artifacts_remote( node_label: "FUGAKU", target_sample_dir: sample_dir_path, sample_name: "advect1d", copy_src_list: ["analysis", "LOG_NUMERROR.peall", "LOG.pe000000_*"] )
      }
      // stage("sample/advect1d_fvm"){
      //   def TEST_RESULT2=sh(script: """
      //       cd ./advect1d_fvm
      //       make clean
      //       make
      //       make run
      //   """) 
      // }
      stage("sample/advdiff1d"){
        // def TEST_RESULT3=sh(script: """
        //     cd ./advdiff1d
        //     make clean
        //     make
        //     make run
        //     export PATH=${env.PATH_ANALYSIS}; export LD_LIBRARY_PATH=${env.LD_LIBRARY_PATH_ANALYSIS}
        //     make vis
        // """)
        com_post.extract_run_LOG_info_remote( node_label: "FUGAKU", target_sample_dir: sample_dir_path, sample_name: "advdiff1d", log_fname: "LOG.pe000000")
        com_post.rsync_sample_artifacts_remote( node_label: "FUGAKU", target_sample_dir: sample_dir_path, sample_name: "advdiff1d", copy_src_list: ["analysis", "LOG_NUMERROR.peall", "LOG.pe000000_*"] )
      }    
      stage("sample/advect2d"){
        // def TEST_RESULT4=sh(script: """
        //     cd ./advect2d
        //     make clean
        //     make
        //     make run
        //     export PATH=${env.PATH_ANALYSIS}; export LD_LIBRARY_PATH=${env.LD_LIBRARY_PATH_ANALYSIS}
        //     make vis
        // """) 
        com_post.extract_run_LOG_info_remote( node_label: "FUGAKU", target_sample_dir: sample_dir_path, sample_name: "advect2d", log_fname: "LOG.pe000000")
        com_post.rsync_sample_artifacts_remote( node_label: "FUGAKU", target_sample_dir: sample_dir_path, sample_name: "advect2d", copy_src_list: ["analysis", "LOG_NUMERROR.peall", "LOG.pe000000_*"] )
      }
      // stage("sample/advect2dGlobal"){
      //   def TEST_RESULT5=sh(script: """
      //       cd ./advect2dGlobal
      //       make clean
      //       make
      //       make run
      //   """) 
      // }      
      // stage("sample/advect2d_fvm"){
      //   def TEST_RESULT6=sh(script: """
      //       cd ./advect2d_fvm
      //       make clean
      //       make
      //       make run
      //   """) 
      // }       
      // stage("sample/advect3d"){
      //   def TEST_RESULT7=sh(script: """
      //       cd ./advect3d
      //       make clean
      //       make
      //       make run
      //   """) 
      // }
      // stage("sample/advect3d_hevi"){
      //   def TEST_RESULT8=sh(script: """
      //       cd ./advect3d_hevi
      //       make clean
      //       make
      //       make run
      //   """) 
      // }
      // stage("sample/euler3d_hevi"){
      //   def TEST_RESULT9=sh(script: """
      //       cd ./euler3d_hevi
      //       make clean
      //       make
      //       make run
      //   """) 
      // }
      // stage("sample/advect3dGlobal"){
      //   def TEST_RESULT10=sh(script: """
      //       cd ./advect3dGlobal
      //       make clean
      //       make
      //       make run
      //   """) 
      // }
      // stage("sample/eigen_analysis"){
      //   def TEST_RESULT11=sh(script: """
      //       cd ./eigen_analysis
      //       make clean
      //       make
      //       make run
      //   """) 
      // }

      stash name: 'sample_artifact', includes: "${env.JOB_NAME}/${env.BUILD_NUMBER}"
    }
  }
}

node('master') {
  unstash 'sample_artifact'
  sh 'ls -l'
}
