#!groovy
nice     = "nice -n 4"

SYSDEP   = "ykworkstation-intel"
BRANCH   = "develop"
MODEL    = "FElib"
TESTCASE = "test"
TESTNAME = ""
TESTTYPE = ""
VERSION  = "XXXXXXX"
STAMP    = "000000000000"

node("master") {
  timestamps {
    def workspace = pwd()
    sh "mkdir -p jenkins-scripts"

    dir("jenkins-scripts") {
        stage ("checkout jenkins-scripts from github") {
            checkout scm: [$class: "GitSCM", branches: [[name: "master"]],
                userRemoteConfigs: [[ credentialsId: "GitHub", url: "git@github.com:ywkawai/FE-Project_jenkins.git" ]]
            ]
        }
    }

    load "${workspace}/jenkins-scripts/common.groovy"

    dir("FE-Project/FElib/src") {
        sh "which mpif90 && mpif90 -v"
        sh "which mpirun && mpirun -V"

        stage ("cleanup") {
            sh "make allclean"
        }

        stage ("build normal") {
            sh "make -j4"
        }
    }

    dir("FE-Project/sample") {
      sh "which mpif90 && mpif90 -v"
      sh "which mpirun && mpirun -V"

      stage("sample/advect1d"){
        def TEST_RESULT1=sh(script: """
            cd ./advect1d
            make clean
            make
            make run
        """) 
      }
      stage("sample/advect1d_fvm"){
        def TEST_RESULT2=sh(script: """
            cd ./advect1d_fvm
            make clean
            make
            make run
        """) 
      }
      stage("sample/advdiff1d"){
        def TEST_RESULT3=sh(script: """
            cd ./advdiff1d
            make clean
            make
            make run
        """) 
      }    
      stage("sample/advect2d"){
        def TEST_RESULT4=sh(script: """
            cd ./advect2d
            make clean
            make
            make run
        """) 
      }
      stage("sample/advect2dGlobal"){
        def TEST_RESULT5=sh(script: """
            cd ./advect2dGlobal
            make clean
            make
            make run
        """) 
      }      
      stage("sample/advect2d_fvm"){
        def TEST_RESULT6=sh(script: """
            cd ./advect2d_fvm
            make clean
            make
            make run
        """) 
      }       
      stage("sample/advect3d"){
        def TEST_RESULT7=sh(script: """
            cd ./advect3d
            make clean
            make
            make run
        """) 
      }
      stage("sample/advect3d_hevi"){
        def TEST_RESULT8=sh(script: """
            cd ./advect3d_hevi
            make clean
            make
            ulimit -s unlimited
            export OMP_STACKSIZE=32m
            make run
        """) 
      }
      stage("sample/euler3d_hevi"){
        def TEST_RESULT9=sh(script: """
            cd ./euler3d_hevi
            make clean
            make
            ulimit -s unlimited
            export OMP_STACKSIZE=32m
            make run
        """) 
      }
      stage("sample/advect3dGlobal"){
        def TEST_RESULT10=sh(script: """
            cd ./advect3dGlobal
            make clean
            make
            make run
        """) 
      }
      stage("sample/eigen_analysis"){
        def TEST_RESULT11=sh(script: """
            cd ./eigen_analysis
            make clean
            make
            make run
        """) 
      }         
    }
  }
}
