#!groovy
nice     = "nice -n 4"

SYSDEP   = "ykworkstation-gnu"
BRANCH   = "develop"
MODEL    = "FElib"
TESTCASE = "test"
TESTNAME = ""
TESTTYPE = ""
VERSION  = "XXXXXXX"
STAMP    = "000000000000"

node("master") {
  timestamps {
    def workspace = pwd()
    sh "mkdir -p jenkins-scripts"
    sh "mkdir -p FE-Project/test_suite"

    dir("jenkins-scripts") {
        stage ("checkout jenkins-scripts from github") {
            checkout scm: [$class: "GitSCM", branches: [[name: "master"]],
                userRemoteConfigs: [[ credentialsId: "GitHub", url: "git@github.com:ywkawai/FE-Project_jenkins.git" ]]
            ]
        }
    }

    load "${workspace}/jenkins-scripts/common.groovy"

    dir("FE-Project/FElib/src") {
        sh "which mpif90 && mpif90 -v"
        sh "which mpirun && mpirun -V"

        stage ("cleanup") {
            sh "make allclean"
        }

        stage ("build normal") {
            sh "make -j4"
        }
    }

    dir("FE-Project/test_suite") {

      sh "which mpif90 && mpif90 -v"
      sh "which mpirun && mpirun -V"

      sh "cp -r ../sample/advect1d ."
      stage("test_suite/advect1d"){
        def TEST_RESULT1=sh(script: """
            cd ./advect1d
            make clean
            make
            make run
        """) 
      }

    }
  }
}
