#!groovy
nice     = "nice -n 10"

SYSDEP   = "ykworkstation-gnu"
BRANCH   = "develop"
MODEL    = "model/atm_nonhydro3d"
TESTCASE = "test"
TESTNAME = ""
TESTTYPE = ""
VERSION  = "XXXXXXX"
STAMP    = "000000000000"

def testlist1 = new Object[13][2]
testlist1[ 0] = [ "tracer_advection     ", "                          " ]
testlist1[ 1] = [ "inertia_gravity_wave ", "                          " ]
testlist1[ 2] = [ "isentropic_vortex    ", "                          " ]
testlist1[ 3] = [ "baroclinic_wave      ", "                          " ]
testlist1[ 4] = [ "density_current      ", "                          " ]
testlist1[ 5] = [ "mountain_wave        ", "linear_hydrostatic_case   " ]
testlist1[ 6] = [ "mountain_wave        ", "linear_nonhydrostatic_case" ]
testlist1[ 7] = [ "mountain_wave        ", "Schaer_case               " ]
testlist1[ 8] = [ "Kelvin_Helmholtz_wave", "                          " ]
testlist1[ 9] = [ "rising_warm_bubble   ", "dry                       " ]
testlist1[10] = [ "rising_warm_bubble   ", "moist                     " ]
testlist1[11] = [ "pbl_turbulence       ", "                          " ]
testlist1[12] = [ "RB_convection        ", "                          " ]

node("master") {
  timestamps {
    def workspace = pwd()
    sh "mkdir -p jenkins-scripts"

    dir("jenkins-scripts") {
        stage ("checkout jenkins-scripts from github") {
            checkout scm: [$class: "GitSCM", branches: [[name: "master"]],
                userRemoteConfigs: [[ credentialsId: "GitHub", url: "git@github.com:ywkawai/FE-Project_jenkins.git" ]]
            ]
        }
    }

    load "${workspace}/jenkins-scripts/common.groovy"

    dir("FE-Project/${MODEL}/src") {
      sh "which mpif90 && mpif90 -v"
      sh "which mpirun && mpirun -V"

      stage ("cleanup (scale-dg)") {
          sh "make allclean"
      }

      stage ("build normal (scale-dg)") {
          sh "make -j4"
      }
    }

    dir("FE-Project/${MODEL}/util/regrid_tool") {
      sh "which mpif90 && mpif90 -v"
      sh "which mpirun && mpirun -V"

      stage ("cleanup (regrid_tool)") {
        sh "make distclean"
      }

      stage ("build normal (regrid_tool)") {
        sh "make -j4"
      }
    }    
    
    dir("FE-Project/${MODEL}/test/case") {
      sh "which mpif90 && mpif90 -v"
      sh "which mpirun && mpirun -V"

      def testcase_dir_path = pwd()
      def com_post = load "${workspace}/jenkins-scripts/common_post.groovy"

      for (int i = 0; i < testlist1.size(); i++) {
        def TESTNAME = testlist1[i][0].trim()
        def TESTTYPE = testlist1[i][1].trim()

        stage ("${TESTNAME} ${TESTTYPE}") {
          dir("${TESTNAME}/${TESTTYPE}"){
            sh "make clean"          
            sh "${nice} make"
            sh "${nice} make run"
            sh "${nice} make vis"
          }
          com_post.extract_run_LOG_info( target_sample_dir: testcase_dir_path, sample_name: "${TESTNAME}/${TESTTYPE}", log_fname: "LOG.pe000000")
          com_post.rsync_sample_artifacts( target_sample_dir: testcase_dir_path, sample_name: "${TESTNAME}/${TESTTYPE}", copy_src_list: ["analysis", "LOG.pe000000_*"] )
        }
      }

    }
  }
}
